<?php
// Call Dwoo_PluginTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'Dwoo_PluginTest::main');
}

require_once 'PHPUnit/Framework.php';

require_once 'Dwoo/Plugin.php';

/**
 * Test class for Dwoo_Plugin.
 * Generated by PHPUnit on 2009-03-11 at 11:28:30.
 */
class Dwoo_PluginTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Dwoo_Plugin
     * @access protected
     */
    protected $object;

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Dwoo_PluginTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Dwoo_Plugin;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testParamsToAttributes().
     */
    public function testParamsToAttributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}

// Call Dwoo_PluginTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Dwoo_PluginTest::main') {
    Dwoo_PluginTest::main();
}
?>
